"""change_qwen_max_3_to_qwen_max

Revision ID: 524e76bb823b
Revises: a433380bbb80
Create Date: 2025-10-24 13:05:22.870370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524e76bb823b'
down_revision: Union[str, Sequence[str], None] = 'a433380bbb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
