"""change_model_name_from_enum_to_string

Revision ID: 558c0c1b4d5a
Revises: 524e76bb823b
Create Date: 2025-10-24 13:21:30.392180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '558c0c1b4d5a'
down_revision: Union[str, Sequence[str], None] = '524e76bb823b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'model_name',
               existing_type=postgresql.ENUM('CLAUDE_SONNET', 'GPT4', 'DEEPSEEK_V3', 'GEMINI_PRO', name='model_name_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'model_name',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CLAUDE_SONNET', 'GPT4', 'DEEPSEEK_V3', 'GEMINI_PRO', name='model_name_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
