"""Complete bot trading system with services

Revision ID: a433380bbb80
Revises: b3bb9d4f2041
Create Date: 2025-10-20 17:35:02.271015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a433380bbb80'
down_revision: Union[str, Sequence[str], None] = 'b3bb9d4f2041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
